services:
  server:
    env_file:
      - ./backend/.env
    build: .
    container_name: go-server
    ports:
      - ${GO_PORT}:8080
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    restart: always

  postgres:
    env_file:
      - ./backend/.env
    image: postgres
    environment:
      - POSTGRES_USER=goserveruser
      - POSTGRES_PASSWORD=goserverpass
      - POSTGRES_DB=mrdb
    volumes:
      - ./backend/initPostgres.sql:/docker-entrypoint-initdb.d
    restart: always