services:
  server:
    build: .
    container_name: go-server
    ports:
      - ${GO_PORT}:8080
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - POSTGRES_CON_STR=${POSTGRES_CON_STR}
      - GO_PORT=${GO_PORT}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./initPostgres.sql:/docker-entrypoint-initdb.d/initPostgres.sql
    restart: always