services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    depends_on:
      - go-server
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
  
  go-server:
    build: .
    container_name: go-server
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - POSTGRES_CON_STR=${POSTGRES_CON_STR}
      - GO_PORT=${GO_PORT}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./initPostgres.sql:/docker-entrypoint-initdb.d/initPostgres.sql
    restart: always