services:
  server:
    build: .
    container_name: go-server
    ports:
      - ${GO_PORT}:8080
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./initPostgres.sql:/docker-entrypoint-initdb.d/initPostgres.sql
    restart: always